/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BoothsGarage;

import static BoothsGarage.DBmethods.*;
import static BoothsGarage.LoginGUI.sr;
import java.sql.SQLException;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Hayes
 */
public class StaffGUI extends javax.swing.JFrame {

    /**
     * Creates new form StaffGUI
     */
    public StaffGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStaffRef = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPostcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAddStaffMember = new javax.swing.JButton();
        btnEditStaffMember = new javax.swing.JButton();
        btnDeleteStaffMember = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        comboDobDay = new javax.swing.JComboBox<>();
        comboDobMonth = new javax.swing.JComboBox<>();
        comboDobYear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Staff");

        jLabel2.setText("Staff Ref.");

        jLabel3.setText("First Name");

        jLabel4.setText("Surname");

        jLabel5.setText("Address");

        jLabel6.setText("Postcode");

        jLabel7.setText("Phone Number");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAddStaffMember.setText("Add Staff Member");
        btnAddStaffMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffMemberActionPerformed(evt);
            }
        });

        btnEditStaffMember.setText("Edit Staff Member");
        btnEditStaffMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffMemberActionPerformed(evt);
            }
        });

        btnDeleteStaffMember.setText("Delete Staff Member");
        btnDeleteStaffMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStaffMemberActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel8.setText("Date of Birth");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        comboDobDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboDobMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        comboDobYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSurname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPostcode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffRef))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddStaffMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditStaffMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteStaffMember, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboDobDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDobMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDobYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 259, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(253, 253, 253))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnAddStaffMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnEditStaffMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnDeleteStaffMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboDobDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboDobMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboDobYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStaffMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffMemberActionPerformed
        String entities = "staff_no, first_name, surname, address, postcode, "
                + "phone_no, dob";
        String staff_no = txtStaffRef.getText();
        String first_name = txtFirstName.getText();
        String surname = txtSurname.getText();
        String address = txtAddress.getText();
        String postcode = txtPostcode.getText();
        String phone_no = txtPhoneNumber.getText();
        String dob = "";
        if(comboDobDay.getSelectedIndex() == 0 
                && comboDobMonth.getSelectedIndex() == 0 
                && comboDobYear.getSelectedIndex() == 0){
            dob = "''";
        }else if(comboDobDay.getSelectedIndex() == 0 
                || comboDobMonth.getSelectedIndex() == 0 
                || comboDobYear.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Incomplete date of birth "
                    + "entered", "Input Error", 
                    JOptionPane.ERROR_MESSAGE);
        }else{
            dob = "TO_DATE ('" + comboDobDay.getSelectedItem().toString() + "-"
                    + comboDobMonth.getSelectedItem().toString() + "-" 
                    + comboDobYear.getSelectedItem().toString() + "')";
        }
        Person p1 = PersonFactory.getInstance("staff");
        p1.setRef(staff_no);
        p1.setFirst_name(first_name);
        p1.setSurname(surname);
        p1.setAddress(address);
        p1.setPostcode(postcode);
        p1.setPhone_no(phone_no);
        p1.setDob(dob);
        String values = p1.toString();
        try {
            DBmethods.insertRecord("staff", entities, values);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerGUI.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddStaffMemberActionPerformed

    private void btnEditStaffMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffMemberActionPerformed
        String where = "staff_no = '" + txtStaffRef.getText() + "'";
        String first_name = txtFirstName.getText();
        String surname = txtSurname.getText();
        String address = txtAddress.getText();
        String postcode = txtPostcode.getText();
        String phone_no = txtPhoneNumber.getText();
        String dob = "";
        if(comboDobDay.getSelectedIndex() == 0 
                && comboDobMonth.getSelectedIndex() == 0 
                && comboDobYear.getSelectedIndex() == 0){
            dob = "''";
        }else if(comboDobDay.getSelectedIndex() == 0 
                || comboDobMonth.getSelectedIndex() == 0 
                || comboDobYear.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Incomplete date of birth "
                    + "entered", "Input Error", 
                    JOptionPane.ERROR_MESSAGE);
        }else{
            dob = "TO_DATE ('" + comboDobDay.getSelectedItem().toString() + "-"
                    + comboDobMonth.getSelectedItem().toString() + "-" 
                    + comboDobYear.getSelectedItem().toString() + "')";
        }
        String set = "";
        set += "first_name = '" + first_name + "'";
        set += ", surname = '" + surname + "'";
        set += ", address = '" + address + "'";
        set += ", postcode = '" + postcode + "'";
        set += ", phone_no = '" + phone_no + "'";
        set += ", dob = " + dob;
        try {
            updateStringRecord("staff", set, where);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerGUI.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditStaffMemberActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        dispose();
        MenuGUI menu = new MenuGUI();
        menu.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        sr.dispose();
        sr = new SearchResults();
        String staff_no = txtStaffRef.getText();
        String first_name = txtFirstName.getText();
        String surname = txtSurname.getText();
        String address = txtAddress.getText();
        String postcode = txtPostcode.getText();
        String phone_no = txtPhoneNumber.getText();
        String dob= "";
        if(comboDobDay.getSelectedIndex() == 0 
                && comboDobMonth.getSelectedIndex() == 0 
                && comboDobYear.getSelectedIndex() == 0){
            dob = "";
        }
        boolean firstTerm = true;
        String where = "";
        if(!staff_no.equalsIgnoreCase("")){
            where += "staff_no IN ('" + staff_no + "')";
            firstTerm = false;
        }
        if(!first_name.equalsIgnoreCase("")){
            if(firstTerm == true){
                where += "first_name IN ('" + first_name + "')";
                firstTerm = false;
            }else{
                where += " AND first_name IN ('" + first_name + "')";
            }
        }
        if(!surname.equalsIgnoreCase("")){
            if(firstTerm == true){
                where += "surname IN ('" + surname + "')";
                firstTerm = false;
            }else{
                where += " AND surname IN ('" + surname + "')";
            }
        }
        if(!address.equalsIgnoreCase("")){
            if(firstTerm == true){
                where += "address IN ('" + address + "')";
                firstTerm = false;
            }else{
                where += " AND address IN ('" + address + "')";
            }
        }
        if(!postcode.equalsIgnoreCase("")){
            if(firstTerm == true){
                where += "postcode IN ('" + postcode + "')";
                firstTerm = false;
            }else{
                where += " AND postcode IN ('" + postcode + "')";
            }
        }
        if(!phone_no.equalsIgnoreCase("")){
            if(firstTerm == true){
                where += "phone_no IN ('" + phone_no + "')";
            }else{
                where += " AND phone_no IN ('" + phone_no + "')";
            }
        }
        if(!dob.equalsIgnoreCase("")){
            if(firstTerm == true){
                where += "dob IN ('" + dob + "')";
            }else{
                where += " AND dob IN ('" + dob + "')";
            }
        }
        try {
            if(where.equalsIgnoreCase("")){
                searchFullTable("staff");
            }else{
                searchWhere("staff", where);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerGUI.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
        sr.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtStaffRef.setText("");
        txtFirstName.setText("");
        txtSurname.setText("");
        txtAddress.setText("");
        txtPostcode.setText("");
        txtPhoneNumber.setText("");
        comboDobDay.setSelectedIndex(0);
        comboDobMonth.setSelectedIndex(0);
        comboDobYear.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteStaffMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffMemberActionPerformed
        String where = "staff_no = '" + txtStaffRef.getText() + "'";
        try {
            deleteRecord("staff", where);
            txtStaffRef.setText("");
            txtFirstName.setText("");
            txtSurname.setText("");
            txtAddress.setText("");
            txtPostcode.setText("");
            txtPhoneNumber.setText("");
            comboDobDay.setSelectedIndex(0);
            comboDobMonth.setSelectedIndex(0);
            comboDobYear.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerGUI.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteStaffMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StaffGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaffMember;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteStaffMember;
    private javax.swing.JButton btnEditStaffMember;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboDobDay;
    private javax.swing.JComboBox<String> comboDobMonth;
    private javax.swing.JComboBox<String> comboDobYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtStaffRef;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
